security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm:   sha1
            encode_as_base64: false
            iterations: 1
            
    providers:
        in_memory:
            users:
                cory:  { password: 321fce77abdd2e917e03783c5096433e26a39bee, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        secured_area:
            pattern:    ^/
            anonymous:  ~
            form_login:
              # the user is redirected here when he/she needs to login
              login_path:                     /login

              # if true, forward the user to the login form instead of redirecting
              use_forward:                    false

              # submit the login form here
              check_path:                     /login_check

              # by default, the login form *must* be a POST, not a GET
              post_only:                      true

              # login success redirecting options (read further below)
              always_use_default_target_path: true
              default_target_path:            /
              target_path_parameter:          _target_path
              use_referer:                    false

              # login failure redirecting options (read further below)
              failure_path:                   null
              failure_forward:                false

              # field names for the username and password fields
              username_parameter:             _username
              password_parameter:             _password

              # csrf token options
              csrf_parameter:                 _csrf_token
              intention:                      authenticate
            logout:
              path:   /logout
              target: /

    access_control:
        - { path: ^/products/add, roles: ROLE_ADMIN }
        - { path: ^/products/update, roles: ROLE_ADMIN }        
        - { path: ^/category/add, roles: ROLE_ADMIN }
        - { path: ^/color/add, roles: ROLE_ADMIN }        
        - { path: ^/designphoto/add, roles: ROLE_ADMIN }