parameters:
#    tshirt_site.example.class: Tshirt\SiteBundle\Example

services:
#    tshirt_site.example:
#        class: %tshirt_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
